version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes

  album-service:
    build:
      context: ./components/album-service
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./components/album-service/:/usr/src/app/
    ports:
      - 10000:8080

  photo-service:
    build:
      context: ./components/photo-service
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./components/photo-service/:/usr/src/app/
    ports:
      - 10001:8080

  subscription-service:
    build:
      context: ./components/subscription-service
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./components/subscription-service/:/usr/src/app/
    ports:
      - 10002:8080

  thumbnail-service:
    build:
      context: ./components/thumbnail-service
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./components/thumbnail-service/:/usr/src/app/
    ports:
      - 10003:8080

  ui-service:
    build:
      context: ./components/ui-service
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./components/ui-service/:/usr/src/app/
    ports:
      - 8080:8080
