version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    entrypoint: redis-server --appendonly yes

  album-service:
    build:
      context: ./components/album-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/album-service/:/usr/src/app/
    ports:
      - 10000:8080
    depends_on:
      - redis

  photo-service:
    build:
      context: ./components/photo-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/photo-service/:/usr/src/app/
    ports:
      - 10001:8080
    depends_on:
      - redis

  subscription-service:
    build:
      context: ./components/subscription-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/subscription-service/:/usr/src/app/
    ports:
      - 10002:8080
    depends_on:
      - redis

  thumbnail-service:
    build:
      context: ./components/thumbnail-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/thumbnail-service/:/usr/src/app/
    ports:
      - 10003:8080
    depends_on:
      - redis

  ui-service:
    build:
      context: ./components/ui-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
      - ALBUM_SERVICE=localhost:10000
      - PHOTO_SERVICE=localhost:10001
      - SUBSCRIPTION_SERVICE=localhost:10002
      - THUMBNAIL_SERVICE=localhost:10003
    volumes:
      - ./components/ui-service/:/usr/src/app/
    ports:
      - 8080:8080
