version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - swg-net
    entrypoint: redis-server

  album-service:
    build: ./components/album-service
    restart: always
    volumes:
      - album-service-data:/usr/src/app/album-service-data
    depends_on:
      - redis
    networks:
      - swg-net

  photo-service:
    build: ./components/photo-service
    restart: always
    volumes:
      - photo-service-data:/usr/src/app/photo-service-data
    depends_on:
      - redis
    networks:
      - swg-net

  subscription-service:
    build: ./components/subscription-service
    restart: always
    volumes:
      - subscription-service-data:/usr/src/app/subscription-service-data
    depends_on:
      - redis
    networks:
      - swg-net

  thumbnail-service:
    build: ./components/thumbnail-service
    restart: always
    volumes:
      - thumbnail-service-data:/usr/src/app/thumbnail-service-data
    depends_on:
      - redis
    networks:
      - swg-net

  ui-service:
    build: ./components/ui-service
    restart: always
    env_file: .env
    networks:
      - swg-net

  proxy:
    image: nginx
    restart: always
    env_file: .env
    volumes:
      - ./swg.template:/etc/nginx/conf.d/swg.template
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
    ports:
      - 80:80
    depends_on:
      - album-service
      - photo-service
      - subscription-service
      - thumbnail-service
      - ui-service
    networks:
      - swg-net
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/swg.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

volumes:
  redis-data:
  album-service-data:
  photo-service-data:
  subscription-service-data:
  thumbnail-service-data:

networks:
  swg-net:
