version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379
    networks:
      - swg-net
    entrypoint: redis-server

  album-service:
    build:
      context: ./components/album-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/album-service/:/usr/src/app/
    networks:
      - swg-net
    depends_on:
      - redis

  photo-service:
    build:
      context: ./components/photo-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/photo-service/:/usr/src/app/
    networks:
      - swg-net
    depends_on:
      - redis

  subscription-service:
    build:
      context: ./components/subscription-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/subscription-service/:/usr/src/app/
    networks:
      - swg-net
    depends_on:
      - redis

  thumbnail-service:
    build:
      context: ./components/thumbnail-service
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/thumbnail-service/:/usr/src/app/
    networks:
      - swg-net
    depends_on:
      - redis

  ui-service:
    build:
      context: ./components/ui-service
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./components/ui-service/:/usr/src/app/
    networks:
      - swg-net

  proxy:
    image: nginx
    restart: always
    env_file: .env
    volumes:
      - ./swg.template:/etc/nginx/conf.d/swg.template
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
    ports:
      - 80:80
    depends_on:
      - album-service
      - photo-service
      - subscription-service
      - thumbnail-service
      - ui-service
    networks:
      - swg-net
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/swg.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  swg-net:
