version: '3'

services:
  album-service:
    build: ./components/album-service
    restart: always
    volumes:
      - swp-album-service-data:/usr/src/app/data
    ports:
      - 10000:8080

  photo-service:
    build: ./components/photo-service
    restart: always
    volumes:
      - swp-photo-service-data:/usr/src/app/data
    ports:
      - 10001:8080

  subscription-service:
    build: ./components/subscription-service
    restart: always
    volumes:
      - swp-subscription-service-data:/usr/src/app/data
    ports:
      - 10002:8080

  thumbnail-service:
    build: ./components/thumbnail-service
    restart: always
    volumes:
      - swp-thumbnail-service-data:/usr/src/app/data
    ports:
      - 10003:8080

  ui-service:
    build: ./components/ui-service
    restart: always
    ports:
      - 8080:8080

volumes:
  swp-album-service-data:
  swp-photo-service-data:
  swp-subscription-service-data:
  swp-thumbnail-service-data:
  swp-ui-service-data:
