version: '3'

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - swg-net
    entrypoint: redis-server --appendonly yes

  album-service:
    build: ./components/album-service
    restart: always
    volumes:
      - album-service-data:/usr/src/app/album-service-data
    ports:
      - 10000:8080

  photo-service:
    build: ./components/photo-service
    restart: always
    volumes:
      - photo-service-data:/usr/src/app/photo-service-data
    ports:
      - 10001:8080

  subscription-service:
    build: ./components/subscription-service
    restart: always
    volumes:
      - subscription-service-data:/usr/src/app/subscription-service-data
    ports:
      - 10002:8080

  thumbnail-service:
    build: ./components/thumbnail-service
    restart: always
    volumes:
      - thumbnail-service-data:/usr/src/app/thumbnail-service-data
    ports:
      - 10003:8080

  ui-service:
    build: ./components/ui-service
    restart: always
    ports:
      - 8080:8080

volumes:
  redis-data:
  album-service-data:
  photo-service-data:
  subscription-service-data:
  thumbnail-service-data:

networks:
  swg-net:
